"""
MALXmlGenerator — builds a MAL-compatible XML import file.

Output format matches the standard MyAnimeList export/import schema:
  <myanimelist>
    <myinfo>...</myinfo>
    <anime>...</anime>
    ...
  </myanimelist>
"""

from __future__ import annotations

import logging
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Optional
from xml.dom import minidom

from .models import AnimeEntry

logger = logging.getLogger(__name__)


class MALXmlGenerator:
    """Generates MAL-compatible XML import files from resolved AnimeEntry objects."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        entries: list[AnimeEntry],
        filepath: Optional[Path] = None,
        user_id: int = 0,
        username: str = "",
    ) -> Path:
        """
        Generate the MAL XML import file.

        Only entries with a resolved MAL ID are included.
        Format matches the official MAL export format.
        """
        filepath = filepath or self.output_dir / "mal_import.xml"

        # Filter to resolved entries only
        resolved = [e for e in entries if e.is_resolved()]
        logger.info(
            "Generating MAL XML: %d resolved entries (out of %d total)",
            len(resolved), len(entries),
        )

        # Build XML manually for precise format control (matching MAL's own export)
        lines: list[str] = []
        lines.append('<?xml version="1.0" encoding="UTF-8" ?>')
        lines.append("\t\t<!--")
        lines.append("\t\t Generated by Trakt-to-MAL Migration Tool")
        lines.append("\t\t Format: MyAnimeList XML Import v1.1.0")
        lines.append("\t\t-->")
        lines.append("")
        lines.append("\t\t<myanimelist>")
        lines.append("")

        # ── User info block ───────────────────────────────────────────
        lines.append("\t\t\t<myinfo>")
        lines.append(f"\t\t\t\t<user_id>{user_id}</user_id>")
        lines.append(f"\t\t\t\t<user_name>{self._escape(username)}</user_name>")
        lines.append("\t\t\t\t<user_export_type>1</user_export_type>")
        lines.append(f"\t\t\t\t<user_total_anime>{len(resolved)}</user_total_anime>")

        # Count by status
        completed = sum(1 for e in resolved if e.status == "Completed")
        watching = sum(1 for e in resolved if e.status == "Watching")
        on_hold = sum(1 for e in resolved if e.status == "On-Hold")
        dropped = sum(1 for e in resolved if e.status == "Dropped")
        plan = sum(1 for e in resolved if e.status == "Plan to Watch")

        lines.append(f"\t\t\t\t<user_total_watching>{watching}</user_total_watching>")
        lines.append(f"\t\t\t\t<user_total_completed>{completed}</user_total_completed>")
        lines.append(f"\t\t\t\t<user_total_onhold>{on_hold}</user_total_onhold>")
        lines.append(f"\t\t\t\t<user_total_dropped>{dropped}</user_total_dropped>")
        lines.append(f"\t\t\t\t<user_total_plantowatch>{plan}</user_total_plantowatch>")
        lines.append("\t\t\t</myinfo>")
        lines.append("")

        # ── Anime entries ─────────────────────────────────────────────
        for entry in resolved:
            lines.append("")
            lines.extend(self._build_anime_block(entry))
            lines.append("")

        lines.append("\t\t\t</myanimelist>")
        lines.append("")

        # Write to file
        content = "\n".join(lines)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info("MAL XML written: %s (%d entries)", filepath.name, len(resolved))
        return filepath

    # ── Private Helpers ───────────────────────────────────────────────────

    def _build_anime_block(self, entry: AnimeEntry) -> list[str]:
        """Build the XML lines for a single <anime> block."""
        title = entry.mal_title or entry.title
        series_type = self._determine_series_type(entry)
        total_eps = entry.mal_total_episodes or entry.total_episodes or 0
        watched_eps = entry.episodes_watched
        start_date = "0000-00-00"
        finish_date = entry.finish_date or "0000-00-00"

        # If not completed, don't set finish date
        if entry.status != "Completed":
            finish_date = "0000-00-00"

        lines = [
            "\t\t\t\t<anime>",
            f"\t\t\t\t\t<series_animedb_id>{entry.mal_id}</series_animedb_id>",
            f"\t\t\t\t\t<series_title><![CDATA[{title}]]></series_title>",
            f"\t\t\t\t\t<series_type>{series_type}</series_type>",
            f"\t\t\t\t\t<series_episodes>{total_eps}</series_episodes>",
            "\t\t\t\t\t<my_id>0</my_id>",
            f"\t\t\t\t\t<my_watched_episodes>{watched_eps}</my_watched_episodes>",
            f"\t\t\t\t\t<my_start_date>{start_date}</my_start_date>",
            f"\t\t\t\t\t<my_finish_date>{finish_date}</my_finish_date>",
            "\t\t\t\t\t<my_rated></my_rated>",
            f"\t\t\t\t\t<my_score>{entry.score}</my_score>",
            "\t\t\t\t\t<my_storage></my_storage>",
            "\t\t\t\t\t<my_storage_value>0.00</my_storage_value>",
            f"\t\t\t\t\t<my_status>{entry.status}</my_status>",
            "\t\t\t\t\t<my_comments><![CDATA[]]></my_comments>",
            "\t\t\t\t\t<my_times_watched>0</my_times_watched>",
            "\t\t\t\t\t<my_rewatch_value></my_rewatch_value>",
            "\t\t\t\t\t<my_priority>LOW</my_priority>",
            "\t\t\t\t\t<my_tags><![CDATA[]]></my_tags>",
            "\t\t\t\t\t<my_rewatching>0</my_rewatching>",
            "\t\t\t\t\t<my_rewatching_ep>0</my_rewatching_ep>",
            "\t\t\t\t\t<my_discuss>1</my_discuss>",
            "\t\t\t\t\t<my_sns>default</my_sns>",
            "\t\t\t\t\t<update_on_import>1</update_on_import>",
            "\t\t\t\t</anime>",
        ]
        return lines

    @staticmethod
    def _determine_series_type(entry: AnimeEntry) -> str:
        """Determine the MAL series type string."""
        if entry.mal_type:
            return entry.mal_type

        if entry.trakt_type == "movie":
            return "Movie"

        # For shows, default to TV
        if entry.season_number == 0:
            return "Special"

        return "TV"

    @staticmethod
    def _escape(text: str) -> str:
        """Escape special XML characters."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;")
        )
